import Banner from "components/home/banner";
import Brands, { Brand } from "components/home/brands";

import client from "@client";
import groq from "groq";
import Head from "next/head";

function Home({ brands }: { brands: Brand[] }) {
  return (
    <div>
      <Head>
        <title>Speakercity</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <Brands brands={brands} />
      </main>
    </div>
  );
}

export default Home;

export async function getStaticProps() {
  const brands = await client.fetch(groq`
	*[_type == "brand"]
	{
		name,
		slug,
		mainImage
	}
    `);

  return {
    props: {
      brands,
    },
  };
}
